# Generated by Django 4.2.3 on 2023-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('marque', models.CharField(blank=True, choices=[('ACCER', 'Accer'), ('DELL', 'DELL'), ('HP', ' HP'), ('LENOVO', 'Lenovo'), ('MAC', 'MAC'), ('Au', 'Autre')], max_length=200, null=True)),
                ('image', models.ImageField(upload_to='product_image')),
                ('categorie', models.CharField(blank=True, choices=[('Ordinateur', 'Ordinateur'), ('Bureautique', 'Bureautique'), ('Stockage', 'Stockage'), ('Connexion', 'Connexion'), ('Electromenager', 'Electromenager')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
