# Generated by Django 4.2.3 on 2023-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('Ordinateur', 'Ordinateur'), ('Bureautique', 'Bureautique'), ('Stockage', 'Stockage'), ('Connexion', 'Connexion'), ('Electromenager', 'Electromenager')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(choices=[('ACCER', 'Accer'), ('DELL', 'DELL'), ('HP', ' HP'), ('LENOVO', 'Lenovo'), ('MAC', 'MAC'), ('Au', 'Autre')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
