# Generated by Django 4.2.3 on 2023-08-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueApp', '0002_alter_product_categorie_alter_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_image/'),
        ),
    ]
